metric: COCO
num_classes: 3

TrainDataset:
  name: COCODataSet
  image_dir: ./
  anno_path: 'annotations/TrainAnnots.json'
  dataset_dir: '/kaggle/working/Original Dataset'
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: ./
  anno_path: 'annotations/ValidationAnnots.json'
  dataset_dir: '/kaggle/working/Original Dataset'
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: 'annotations/TestAnnots.json' # also support txt (like VOC's label_list.txt)
  dataset_dir: '/kaggle/working/Original Dataset' # if set, anno_path will be 'dataset_dir/anno_path'
